# written by tode --shortcut-setup — frees the chords the editor needs from kitty
map ctrl+shift+c copy_or_noop
map ctrl+shift+o
map ctrl+shift+h
map ctrl+shift+g
map ctrl+shift+/
map ctrl+shift+enter
map ctrl+shift+]
map ctrl+shift+[
map ctrl+shift+f
map ctrl+shift+b
map ctrl+shift+`
map ctrl+shift+r
map ctrl+shift+1
map ctrl+shift+2
map ctrl+shift+5
map ctrl+shift+6
map ctrl+shift+right
map ctrl+shift+left
map ctrl+shift+tab
map ctrl+shift+t
map ctrl+shift+.
map ctrl+shift+,
map ctrl+shift+l
map ctrl+shift+-
map ctrl+shift+backspace
map ctrl+shift+e
map ctrl+shift+p
map ctrl+shift+f3
map ctrl+shift+f10
map ctrl+shift+f2
map ctrl+shift+a
map ctrl+shift+f5
map ctrl+0
map shift+alt+.
map shift+alt+q
map alt+t
map alt+;
map alt+f
