#     finger_count: 1-5
#     gesture_types: [t]ap  [h]old
#                    pinch [i]n and pinch [o]ut
#     swipe_gesture: [l]eft [r]ight [u]p [d]own
#
#     0  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95 100
#    0┌──────────────────────┬───────────────────────────────────────────┬───────────┐
#    5│ > media_area (1f)    │ > main_neutral_area                       │           │
#   10│     forword          │ 3t middleClick 3h screensht 3i overview   │           │
#   20│ previous  next       │ 3lr Volume     3ud Brightns 3o fullscreen │           │
#   15│     backward         │ 4t paste       4h copy      4i tabReopn   │           │
#   25│ 1t    play_pause     │ 4lr TabBackFwd 4ud TabChnge 4o tabClose   │           │
#   30│                      │ 5t play-pause  5h clipboard               │           │
#   35│                      │                                           │           │
#   40├──────────────────────│                                           │           │
#   45│                      │                                           │           │
#   50│ movement (s1)        │                                           │           │
#   55│ 1s dir 1t ent 1h esc │                                           │           │
#   60│ 2lr del/bs   2t bs   │                                           │           │
#   65│ 2ud undo/redo        │                                           │           │
#   70│       ctrl-z         │                                           │           │
#   75│ 2l       ↑           │                                           │           │
#   80│ hom ← ent/esc → end  ├───────────────────────────────────────────┴───────────┤
#   85│          ↓           │                                                       │
#   90│       ctrl-y         │                                                       │
#   95│ 3t ctrl-l 3h ctrl-t  │                                                       │
#  100└──────────────────────┴───────────────────────────────────────────────────────┘

device_rules:
  - conditions: $touchpad
    swipe:
      angle_tolerance: 45

touchpad:
  gestures:
    # media zone top left {{{
    - type: swipe
      fingers: 1
      direction: up_down
      conditions:
        - &zone_media_x $finger_1_initial_position_percentage_x <= 0.30
        - &zone_media_y $finger_1_initial_position_percentage_y < 0.40
      actions:
        - on: update
          interval: -20
          command: playerctl position 3+
        - on: update
          interval: 30
          command: playerctl position 3-

    - type: swipe
      fingers: 1
      direction: left_right
      conditions:
        - *zone_media_x
        - *zone_media_y
      actions:
        - on: update
          interval: -200
          command: playerctl previous
        - on: update
          interval: 200
          command: playerctl next

    # control width of the current window
    - type: swipe
      fingers: 2
      direction: left_right
      conditions:
        - *zone_media_x
        - *zone_media_y
      actions:
        - on: update
          interval: -60
          input:
            - keyboard: [leftmeta+leftshift+left]
        - on: update
          interval: 60
          input:
            - keyboard: [leftmeta+leftshift+right]

    - type: tap
      fingers: 1
      conditions:
        - *zone_media_x
        - *zone_media_y
      actions:
        - on: update
          command: playerctl play-pause
    # }}}

    # bottom zone {{{
    - type: tap
      fingers: 1
      conditions:
        - &zone_bottom_x $finger_1_initial_position_percentage_x > 0.30
        - &zone_bottom_y $finger_1_initial_position_percentage_y >= 0.80
      actions:
        - on: begin
          input:
            - keyboard: [leftmeta+grave]

    # screenshot
    - type: tap
      fingers: 2
      conditions:
        - *zone_bottom_x
        - *zone_bottom_y
      actions:
        - on: begin
          input:
            - keyboard: [leftmeta+leftshift+s]

    # movement zone bottom left_right
    - type: swipe
      fingers: 1
      direction: left_right
      conditions:
        - *zone_bottom_x
        - *zone_bottom_y
      actions:
        - on: update
          interval: -40
          input:
            - keyboard: [left]
        - on: update
          interval: 40
          input:
            - keyboard: [right]
      # }}}

# movement zone bottom left {{{
    - type: swipe
      fingers: 1
      direction: left_right
      conditions:
        - &zone_movement_x $finger_1_initial_position_percentage_x <= 0.30
        - &zone_movement_y $finger_1_initial_position_percentage_y >= 0.40
      actions:
        - on: update
          interval: -40
          input:
            - keyboard: [left]
        - on: update
          interval: 40
          input:
            - keyboard: [right]

    - type: swipe
      fingers: 1
      direction: up_down
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: update
          interval: -40
          input:
            - keyboard: [up]
        - on: update
          interval: 40
          input:
            - keyboard: [down]

    - type: swipe
      fingers: 2
      direction: left_right
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: update
          interval: -40
          input:
            - keyboard: [home]
        - on: update
          interval: 40
          input:
            - keyboard: [end]

    - type: swipe
      fingers: 2
      direction: up_down
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: update
          interval: -60
          input:
            - keyboard: [leftctrl+z]
        - on: update
          interval: 60
          input:
            - keyboard: [leftctrl+y]

    - type: tap
      fingers: 1
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: begin
          input:
            - keyboard: [enter]

    - type: hold
      fingers: 1
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: begin
          input:
            - keyboard: [esc]

    - type: tap
      fingers: 2
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: update
          input:
            - keyboard: [backspace]

    - type: hold
      fingers: 2
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: tick
          input:
            - keyboard: [backspace]

    - type: tap
      fingers: 3
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+a]

    - type: hold
      fingers: 3
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+t]

    - type: swipe
      fingers: 3
      direction: up_down
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: update
          interval: -40
          input:
            - keyboard: [pageup]
        - on: update
          interval: 40
          input:
            - keyboard: [PageDown]

    - type: tap
      fingers: 4
      conditions:
        - *zone_movement_x
        - *zone_movement_y
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+l]

# }}}

# # zone center right and top right alt-tab {{{

    # - type: tap
    #   fingers: 1
    #   conditions:
    #     - &zone_center_right_x $finger_1_initial_position_percentage_x >= 0.85
    #     - &zone_center_right_y1 $finger_1_initial_position_percentage_y < 0.80
    #     - &zone_center_right_y2 $finger_1_initial_position_percentage_y >= 0.30
    #   actions:
    #     - on: update
    #       input:
    #         - keyboard: [leftctrl+leftmeta+p]

    # - type: hold
    #   fingers: 1
    #   conditions:
    #     - *zone_center_right_x
    #     - *zone_center_right_y1
    #     - *zone_center_right_y2
    #   actions:
    #     - on: begin
    #       input:
    #         - keyboard: [leftctrl+leftmeta+c]

    # - type: tap
    #   fingers: 1
    #   conditions:
    #     - &zone_top_right_x $finger_1_initial_position_percentage_x >= 0.85
    #     - &zone_top_right_y $finger_1_initial_position_percentage_y < 0.30
    #   actions:
    #     - on: update
    #       input:
    #         - keyboard: [leftctrl+leftmeta+n]

    # - type: hold
    #   fingers: 1
    #   conditions:
    #     - *zone_top_right_x
    #     - *zone_top_right_y
    #   actions:
    #     - on: begin
    #       input:
    #         - keyboard: [leftctrl+leftmeta+c]

# }}}

# default zone / gestures {{{

    # brightness up&down / global
    - type: swipe
      fingers: 3
      direction: up_down
      actions:
        - on: update
          interval: -20
          input:
            - keyboard: [leftshift+brightnessup]
        - on: update
          interval: 20
          input:
            - keyboard: [leftshift+brightnessdown]

    # brightness up&down / global
    - type: swipe
      fingers: 3
      direction: left_right
      actions:
        - on: update
          interval: -10
          input:
            - keyboard: [volumedown]
        - on: update
          interval: 10
          input:
            - keyboard: [volumeup]

    # 4 fingers
    # go forward / global
    - type: swipe
      fingers: 4
      direction: left
      actions:
        - on: begin
          input:
            - mouse: [forward]

    # go back / global
    - type: swipe
      fingers: 4
      direction: right
      actions:
        - on: begin
          input:
            - mouse: [back]

    # previous/next tab
    - type: swipe
      fingers: 4
      direction: up_down
      actions:
        - on: update
          interval: -80
          input:
            - keyboard: [leftctrl+leftshift+tab]
        - on: update
          interval: 80
          input:
            - keyboard: [leftctrl+tab]

    # undo close tab
    - type: pinch
      fingers: 4
      direction: in
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+leftshift+t]

    # close tab
    - type: pinch
      fingers: 4
      direction: out
      actions:
        - on: begin
          # interval: 10
          input:
            - keyboard: [leftctrl+w]

    # paste on kitty
    - type: tap
      fingers: 4
      conditions:
        - $window_class == "kitty"
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+leftshift+v]


    - type: tap
      fingers: 4
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+v]

    # copy on kitty
    - type: hold
      fingers: 4
      conditions:
        - $window_class == "kitty"
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+leftshift+c]

    # general copy
    - type: hold
      fingers: 4
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+c]

    - type: tap
      fingers: 5
      actions:
        - on: begin
          input:
            - keyboard: [leftalt+f4]

    - type: hold
      fingers: 5
      actions:
        - on: begin
          input:
            - keyboard: [leftmeta+v]


    # - type: tap
    #   fingers: 3
    #   actions:
    #     - on: begin
    #       input:
    #         - mouse: [middle]

    # - type: hold
    #   fingers: 3
    #   actions:
    #     - on: begin
    #       input:
    #         - keyboard: [leftmeta+leftshift+s]

    - type: pinch
      fingers: 3
      direction: out
      actions:
        - on: begin
          input:
            - keyboard: [leftmeta+f]

    - type: pinch
      fingers: 3
      direction: in
      actions:
        - on: begin
          input:
            - keyboard: [leftctrl+f10]
# }}}
