#!/bin/bash

# Check current color scheme from kdeglobals
current_scheme=$(kreadconfig6 --file kdeglobals --group General --key ColorScheme)

if [ "$current_scheme" = "BreezeLight" ]; then
    plasma-apply-lookandfeel -a org.kde.breezedark.desktop
    plasma-apply-wallpaperimage ~/Pictures/wallpapers/dark.png
else
    plasma-apply-lookandfeel -a org.kde.breeze.desktop
    plasma-apply-wallpaperimage ~/Pictures/wallpapers/light.png
fi
